server:
  port: ${PARSER_PORT:8080}
  servlet:
    context-path: /parser
spring:
  application:
    name: parser
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:imocha-db}?ssl=false
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false